title       = "vietstock"
baseURL     = "https://vietstock-cli.tamnd.com/"
description = "A command line for vietstock."
contentDir  = "content"
outputDir   = "public"
theme       = "tago-doks"
syntaxHighlight = "true"

[params]
github = "https://github.com/tamnd/vietstock-cli"
